%% Step 5: Comparison of All Filters
load('ecg_data.mat');
load('butter_result.mat');
load('cheby_result.mat');
load('fir_result.mat');
%% Time-Domain Comparison
figure;
subplot(4,1,1);plot(timeAxis,noisyEcgSignal);title('Noisy ECG');ylabel('mV');grid on;
subplot(4,1,2);plot(timeAxis,ecgCleanedButterworth);title('Butterworth Filtered');ylabel('mV');grid on;
subplot(4,1,3);plot(timeAxis,ecgCleanedChebyshev);title('Chebyshev Filtered');ylabel('mV');grid on;
subplot(4,1,4);plot(timeAxis,ecgCleanedFir);title('FIR Filtered');ylabel('mV');xlabel('Time (s)');grid on;
%% PSD Comparison
[psdNoisySignal,psdFreqAxis]=pwelch(noisyEcgSignal,hamming(512),256,1024,samplingFrequency);
[psdButterworthSignal,~]=pwelch(ecgCleanedButterworth,hamming(512),256,1024,samplingFrequency);
[psdChebyshevSignal,~]=pwelch(ecgCleanedChebyshev,hamming(512),256,1024,samplingFrequency);
[psdFirSignal,~]=pwelch(ecgCleanedFir,hamming(512),256,1024,samplingFrequency);
figure;
plot(psdFreqAxis,10*log10(psdNoisySignal),'m');hold on;
plot(psdFreqAxis,10*log10(psdButterworthSignal),'b');
plot(psdFreqAxis,10*log10(psdChebyshevSignal),'r');
plot(psdFreqAxis,10*log10(psdFirSignal),'g');
legend('Noisy','Butterworth','Chebyshev','FIR');
xlabel('Frequency (Hz)');ylabel('Power/Frequency (dB/Hz)');
title('PSD Comparison: All Filters');xlim([0 180]);grid on;
xline(0.5,'--c','0.5 Hz');xline(50,'--m','50 Hz');xline(100,'--y','100 Hz');
%% Spectrograms
figure;
subplot(2,2,1);spectrogram(noisyEcgSignal,hamming(256),128,512,samplingFrequency,'yaxis');title('Spectrogram (Noisy ECG)');
subplot(2,2,2);spectrogram(ecgCleanedButterworth,hamming(256),128,512,samplingFrequency,'yaxis');title('Spectrogram (Butterworth)');
subplot(2,2,3);spectrogram(ecgCleanedChebyshev,hamming(256),128,512,samplingFrequency,'yaxis');title('Spectrogram (Chebyshev)');
subplot(2,2,4);spectrogram(ecgCleanedFir,hamming(256),128,512,samplingFrequency,'yaxis');title('Spectrogram (FIR)');
%% SNR
removedNoiseButter=noisyEcgSignal-ecgCleanedButterworth;
removedNoiseCheby=noisyEcgSignal-ecgCleanedChebyshev;
removedNoiseFir=noisyEcgSignal-ecgCleanedFir;
outputSnrButterworth=10*log10(sum(ecgCleanedButterworth.^2)/sum(removedNoiseButter.^2));
outputSnrChebyshev=10*log10(sum(ecgCleanedChebyshev.^2)/sum(removedNoiseCheby.^2));
outputSnrFir=10*log10(sum(ecgCleanedFir.^2)/sum(removedNoiseFir.^2));
fprintf('SNR indicator Butterworth : %.2f dB\n',outputSnrButterworth);
fprintf('SNR indicator Chebyshev   : %.2f dB\n',outputSnrChebyshev);
fprintf('SNR indicator FIR         : %.2f dB\n',outputSnrFir);
%% Phase Response Comparison - High-Pass
freqResponsePoints=8192;
[butterworthHpFreqResponse,highPassFreqAxis]=freqz(butterworthHpNumerator,butterworthHpDenominator,freqResponsePoints,samplingFrequency);
[chebyshevHpFreqResponse,~]=freqz(chebyshevHpNumerator,chebyshevHpDenominator,freqResponsePoints,samplingFrequency);
[firHpFreqResponse,~]=freqz(firHighPassNumerator,1,freqResponsePoints,samplingFrequency);
figure;
subplot(2,1,1);
plot(highPassFreqAxis,20*log10(abs(butterworthHpFreqResponse)),'b','LineWidth',1.4);hold on;
plot(highPassFreqAxis,20*log10(abs(chebyshevHpFreqResponse)),'r','LineWidth',1.4);
plot(highPassFreqAxis,20*log10(abs(firHpFreqResponse)),'g','LineWidth',1.4);
xline(0.5,'--m','0.5 Hz');ylim([-80 5]);xlim([0 5]);
legend('Butterworth HP','Chebyshev HP','FIR HP','Location','southeast');
xlabel('Frequency (Hz)');ylabel('Magnitude (dB)');
title('High-Pass: Magnitude Response Comparison');grid on;
subplot(2,1,2);
plot(highPassFreqAxis,unwrap(angle(butterworthHpFreqResponse))*180/pi,'b','LineWidth',1.4);hold on;
plot(highPassFreqAxis,unwrap(angle(chebyshevHpFreqResponse))*180/pi,'r','LineWidth',1.4);
plot(highPassFreqAxis,unwrap(angle(firHpFreqResponse))*180/pi,'g','LineWidth',1.4);
xline(0.5,'--g','0.5 Hz');xlim([0 10]);
legend('Butterworth HP','Chebyshev HP','FIR HP','Location','northeast');
xlabel('Frequency (Hz)');ylabel('Phase (degrees)');
title('High-Pass: Phase Response Comparison');grid on;
%% Phase Response Comparison - Low-Pass
[butterworthLpFreqResponse,lowPassFreqAxis]=freqz(butterworthLpNumerator,butterworthLpDenominator,freqResponsePoints,samplingFrequency);
[chebyshevLpFreqResponse,~]=freqz(chebyshevLpNumerator,chebyshevLpDenominator,freqResponsePoints,samplingFrequency);
[firLpFreqResponse,~]=freqz(firLowPassNumerator,1,freqResponsePoints,samplingFrequency);
figure;
subplot(2,1,1);
plot(lowPassFreqAxis,20*log10(abs(butterworthLpFreqResponse)),'b','LineWidth',1.4);hold on;
plot(lowPassFreqAxis,20*log10(abs(chebyshevLpFreqResponse)),'r','LineWidth',1.4);
plot(lowPassFreqAxis,20*log10(abs(firLpFreqResponse)),'g','LineWidth',1.4);
xline(100,'--r','100 Hz');xline(150,'m--','150 Hz');ylim([-100 5]);xlim([0 180]);
legend('Butterworth LP','Chebyshev LP','FIR LP','Location','southwest');
xlabel('Frequency (Hz)');ylabel('Magnitude (dB)');
title('Low-Pass: Magnitude Response Comparison');grid on;
subplot(2,1,2);
plot(lowPassFreqAxis,unwrap(angle(butterworthLpFreqResponse))*180/pi,'b','LineWidth',1.4);hold on;
plot(lowPassFreqAxis,unwrap(angle(chebyshevLpFreqResponse))*180/pi,'r','LineWidth',1.4);
plot(lowPassFreqAxis,unwrap(angle(firLpFreqResponse))*180/pi,'g','LineWidth',1.4);
xline(100,'--g','100 Hz');xlim([0 180]);
legend('Butterworth LP','Chebyshev LP','FIR LP','Location','southwest');
xlabel('Frequency (Hz)');ylabel('Phase (degrees)');
title('Low-Pass: Phase Response Comparison');grid on;
%% Group Delay Comparison
figure;
subplot(2,1,1);
[groupDelayButterworthHp,groupDelayFreqAxis]=grpdelay(butterworthHpNumerator,butterworthHpDenominator,freqResponsePoints,samplingFrequency);
[groupDelayChebyshevHp,~]=grpdelay(chebyshevHpNumerator,chebyshevHpDenominator,freqResponsePoints,samplingFrequency);
[groupDelayFirHp,~]=grpdelay(firHighPassNumerator,1,freqResponsePoints,samplingFrequency);
plot(groupDelayFreqAxis,groupDelayButterworthHp,'b','LineWidth',1.4);hold on;
plot(groupDelayFreqAxis,groupDelayChebyshevHp,'r','LineWidth',1.4);
plot(groupDelayFreqAxis,groupDelayFirHp,'g','LineWidth',1.4);
xline(0.5,'--y','0.5 Hz');xlim([0 10]);
legend('Butterworth HP','Chebyshev HP','FIR HP');
xlabel('Frequency (Hz)');ylabel('Group Delay (samples)');
title('High-Pass: Group Delay Comparison');grid on;
subplot(2,1,2);
[groupDelayButterworthLp,groupDelayLpFreqAxis]=grpdelay(butterworthLpNumerator,butterworthLpDenominator,freqResponsePoints,samplingFrequency);
[groupDelayChebyshevLp,~]=grpdelay(chebyshevLpNumerator,chebyshevLpDenominator,freqResponsePoints,samplingFrequency);
[groupDelayFirLp,~]=grpdelay(firLowPassNumerator,1,freqResponsePoints,samplingFrequency);
plot(groupDelayLpFreqAxis,groupDelayButterworthLp,'b','LineWidth',1.4);hold on;
plot(groupDelayLpFreqAxis,groupDelayChebyshevLp,'r','LineWidth',1.4);
plot(groupDelayLpFreqAxis,groupDelayFirLp,'g','LineWidth',1.4);
xline(100,'--m','100 Hz');xlim([0 180]);
legend('Butterworth LP','Chebyshev LP','FIR LP');
xlabel('Frequency (Hz)');ylabel('Group Delay (samples)');
title('Low-Pass: Group Delay Comparison');grid on;
%% Removed Noise Plots
figure;
subplot(3,1,1);plot(timeAxis,removedNoiseButter);title('Removed Noise (Butterworth)');xlabel('Time (s)');ylabel('mV');grid on;
subplot(3,1,2);plot(timeAxis,removedNoiseCheby);title('Removed Noise (Chebyshev)');xlabel('Time (s)');ylabel('mV');grid on;
subplot(3,1,3);plot(timeAxis,removedNoiseFir);title('Removed Noise (FIR)');xlabel('Time (s)');ylabel('mV');grid on;
